import type { Metadata } from 'next';
import '@/styles/global.css';
import { QueryProvider } from '@/provider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Navigator } from '@/components/base';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.5/kakao.min.js"
          integrity="sha384-dok87au0gKqJdxs7msEdBPNnKSRT+/mhTVzq+qOhcL464zXwvcrpjeWvyj1kCdq6"
          crossOrigin="anonymous"
        ></script>
      </head>

      <body>
        <QueryProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          {children}
          <Navigator/>
        </QueryProvider>
      </body>
    </html>
  );
}
