import type { Metadata } from 'next';
import '@/styles/global.css';
import { QueryProvider } from '@/provider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>

      <body>
        <QueryProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          {children}
          {/* <Navigator/> */}
        </QueryProvider>
      </body>
    </html>
  );
}
