import { ApiCalendarEventType, CalendarEventType } from '@/@types/calendar';

export const calendarEventsNone = [];

export const calendarEvents: CalendarEventType[] = [
  {
    id: 0,
    calendarId: 123,
    title: '네이버',
    allDay: true,
    startDate: new Date('2025-08-17T10:00:00'),
    endDate: new Date('2025-08-17T12:00:00'),
    repeatCycle: null,
    color: 'yoteyoGreen',
    locate: '잠실 롯데월드몰',
    memo: '무신사 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '카카오톡 선물하기',
    allDay: true,
    startDate: new Date('2025-08-09T09:00:00'),
    endDate: new Date('2025-08-13T12:00:00'),
    repeatCycle: 'week',
    color: 'yoteyoOrange',
    locate: '전국 스타벅스',
    memo: '이마트 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: 'G마켓',
    allDay: true,
    startDate: new Date('2025-08-01T13:00:00'),
    endDate: new Date('2025-08-02T14:00:00'),
    repeatCycle: null,
    color: 'yoteyoRed',
    locate: '다이소 본사',
    memo: '쿠팡 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '무인양품',
    allDay: true,
    startDate: new Date('2025-08-05T13:00:00'),
    endDate: new Date('2025-08-06T17:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '홍대 무신사 스튜디오',
    memo: '네이버 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '11번가',
    allDay: true,
    startDate: new Date('2025-08-04T10:00:00'),
    endDate: new Date('2025-08-06T14:00:00'),
    repeatCycle: null,
    color: 'yoteyoGreen',
    locate: '강남 현대백화점',
    memo: 'G마켓 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '스타벅스',
    allDay: true,
    startDate: new Date('2025-08-05T11:00:00'),
    endDate: new Date('2025-08-07T15:00:00'),
    repeatCycle: 'day',
    color: 'yoteyoOrange',
    locate: '쿠팡 풀필먼트 센터',
    memo: '11번가 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '위메프',
    allDay: true,
    startDate: new Date('2025-08-06T09:00:00'),
    endDate: new Date('2025-08-06T13:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '무인양품 압구정점',
    memo: '스타벅스 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '카카오톡 선물하기',
    allDay: true,
    startDate: new Date('2025-08-02T14:00:00'),
    endDate: new Date('2025-08-06T18:00:00'),
    repeatCycle: 'month',
    color: 'yoteyoGreen',
    locate: '마켓컬리 본사',
    memo: 'GS25 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: 'G마켓',
    allDay: true,
    startDate: new Date('2025-08-05T14:00:00'),
    endDate: new Date('2025-08-08T16:00:00'),
    repeatCycle: null,
    color: 'yoteyoGreen',
    locate: '홍대 무신사 스튜디오',
    memo: '현대백화점 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '다이소',
    allDay: true,
    startDate: new Date('2025-08-06T13:00:00'),
    endDate: new Date('2025-08-07T17:00:00'),
    repeatCycle: null,
    color: 'yoteyoRed',
    locate: '강남 현대백화점',
    memo: '신세계백화점 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '홈플러스',
    allDay: true,
    startDate: new Date('2025-08-01T09:00:00'),
    endDate: new Date('2025-08-03T12:00:00'),
    repeatCycle: 'day',
    color: 'yoteyoEmerald',
    locate: '전국 이마트 매장',
    memo: '홈플러스 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '쿠팡',
    allDay: true,
    startDate: new Date('2025-08-03T13:00:00'),
    endDate: new Date('2025-08-04T15:00:00'),
    repeatCycle: null,
    color: 'yoteyoRed',
    locate: '무인양품 압구정점',
    memo: '무신사 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '무인양품',
    allDay: true,
    startDate: new Date('2025-08-06T10:00:00'),
    endDate: new Date('2025-08-08T14:00:00'),
    repeatCycle: null,
    color: 'yoteyoOrange',
    locate: '잠실 롯데월드몰',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '무신사',
    allDay: true,
    startDate: new Date('2025-08-04T14:00:00'),
    endDate: new Date('2025-08-07T16:00:00'),
    repeatCycle: 'week',
    color: 'yoteyoEmerald',
    locate: '다이소 본사',
    memo: '이마트 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '세븐일레븐',
    allDay: true,
    startDate: new Date('2025-08-06T10:00:00'),
    endDate: new Date('2025-08-10T14:00:00'),
    repeatCycle: null,
    color: 'yoteyoPurple',
    locate: '전국 스타벅스',
    memo: '쿠팡 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '무신사',
    allDay: true,
    startDate: new Date('2025-08-02T13:00:00'),
    endDate: new Date('2025-08-06T17:00:00'),
    repeatCycle: null,
    color: 'yoteyoGreen',
    locate: '홍대 무신사 스튜디오',
    memo: '네이버 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '카카오톡 선물하기',
    allDay: true,
    startDate: new Date('2025-08-07T09:00:00'),
    endDate: new Date('2025-08-08T13:00:00'),
    repeatCycle: null,
    color: 'yoteyoBlue',
    locate: '전국 올리브영 매장',
    memo: '이마트 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '스타벅스',
    allDay: true,
    startDate: new Date('2025-08-05T14:00:00'),
    endDate: new Date('2025-08-07T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '스타벅스30',
    allDay: true,
    startDate: new Date('2025-08-07T14:00:00'),
    endDate: new Date('2025-08-07T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영30',
    allDay: true,
    startDate: new Date('2025-08-07T14:00:00'),
    endDate: new Date('2025-08-07T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영30',
    allDay: true,
    startDate: new Date('2025-08-28T14:00:00'),
    endDate: new Date('2025-08-28T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영31',
    allDay: true,
    startDate: new Date('2025-08-28T14:00:00'),
    endDate: new Date('2025-08-28T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영32',
    allDay: true,
    startDate: new Date('2025-08-28T14:00:00'),
    endDate: new Date('2025-08-28T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영33',
    allDay: true,
    startDate: new Date('2025-08-28T14:00:00'),
    endDate: new Date('2025-08-28T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영34',
    allDay: true,
    startDate: new Date('2025-08-28T14:00:00'),
    endDate: new Date('2025-08-28T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영35',
    allDay: true,
    startDate: new Date('2025-08-28T14:00:00'),
    endDate: new Date('2025-08-28T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영36',
    allDay: true,
    startDate: new Date('2025-08-28T14:00:00'),
    endDate: new Date('2025-08-28T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
  {
    id: 0,
    calendarId: 123,
    title: '올리브영37',
    allDay: true,
    startDate: new Date('2025-08-28T14:00:00'),
    endDate: new Date('2025-08-28T18:00:00'),
    repeatCycle: null,
    color: 'yoteyoEmerald',
    locate: '전국 스타벅스',
    memo: '올리브영 관련 세일 이벤트',
    holiday: false,
    isPending: false,
    isYoteyo: false,
  },
];

export const calendarApiResponse: ApiCalendarEventType[] = [
  {
    id: 1,
    calendarId: 1,
    title: '2025 무신사 블랙 프라이데이',
    allDay: true,
    startDate: '2025-08-26T00:00:00',
    endDate: '2025-08-26T23:59:59',
    repeatCycle: null,
    color: 'yoteyoPurple',
    locate: '서울 강남 무신사 매장',
    memo: '최대 80% 할인, 오프라인 이벤트 포함',
    holiday: false,
    // isPending:false,
    // isYoteyo:false
  },
];
